# Generated by Django 5.1.7 on 2025-03-25 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_level', models.FloatField()),
                ('pressure_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity_level', models.FloatField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
