# Generated by Django 5.1.7 on 2025-03-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherMeasures',
            new_name='Measures',
        ),
        migrations.RenameModel(
            old_name='WeatherUsers',
            new_name='Users',
        ),
    ]
