# Generated by Django 5.1.7 on 2025-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0002_rename_weathermeasures_measures_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measures',
            new_name='Measure',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
